### ISSUE TITLE
リリース準備

### ISSUE THREAD

**Issue by nkthkr** [Kenny-NISLab/nislab#3]
fabicon,OGP等設定

**Comment by kogepanh** [comment]
トップページ以外では、headのtitleが `タイトル｜NISLAB` になるようにしてほしいです！

**Comment by nkthkr** [comment]
記事ページのOGPのdescriptionどうしますか

**Comment by kogepanh** [comment]
できれば、各ページのbody部分の一段落目とかにできたらと思うけど、そもそもベストプラクティス的なんがわからんので任せます笑

なんかいい感じの案ある？

**Comment by nkthkr** [comment]
body部分にしようとするとmarkdown形式のままかHTMLタグが入った状態になっちゃうのでそれらを省く面倒な処理をしないといけない気がする．contentfulにdescription fieldsを作っておくべきでしたが今更すぎるからサイト自体のdescriptionで統一するのが無難かなあ．．

**Comment by kogepanh** [comment]
全然それでいいと思う！
Contentfulの管理する量増やすと面倒やし、佐藤先生が書く記事とかでそんなん設定してくれると思えへんしな笑
