### ISSUE TITLE
デザイン微調整

### ISSUE THREAD

**Issue by nkthkr** [Kenny-NISLab/nislab#58]

**Comment by kogepanh** [comment]
PC で見た時に、 Members ページとかの Table が横スクロールバーが出てるのが若干気になるかもです

![スクリーンショット 2021-07-13 12 32 34](https://user-images.githubusercontent.com/49851726/125386006-86dbf280-e3d6-11eb-9e02-a900677d9b47.png)

**Comment by kogepanh** [comment]
Table のなかで `<br/>` タグを使いたい時もあるので、 Markdown に書いた HTML タグが反映されるようにしてほしいです

![スクリーンショット 2021-07-13 12 35 42](https://user-images.githubusercontent.com/49851726/125386272-f2be5b00-e3d6-11eb-8f50-771a50a4cf2e.png)

**Comment by kogepanh** [comment]
各ページの最下部に表示されるグレーの横バーは何者？
PCで表示する分にはいらなさそうなら、消して欲しいです

![スクリーンショット 2021-07-13 12 37 28](https://user-images.githubusercontent.com/49851726/125386401-2dc08e80-e3d7-11eb-8894-e7eed3a6a2fe.png)

**Comment by nkthkr** [comment]
> 各ページの最下部に表示されるグレーの横バーは何者？
PCで表示する分にはいらなさそうなら、消して欲しいです

これだけこっちの環境で確認できてないので修正できてるか教えてください

**Comment by nkthkr** [comment]
tableのline-heightを全部狭くすることなら対応可(改行なしの場合も狭くなる)

**Comment by kogepanh** [comment]
それでいいんちゃうかな
上下の羅線より隙間が空いてるのはなんか違和感を感じるし

**Comment by kogepanh** [comment]
ありがと！

**Comment by yoshikity** [comment]
卒業生の実績の「DMM.com」の部分がリンクになってて，表示が崩れてます．

<img width="1440" alt="スクリーンショット 2021-07-13 16 22 13" src="https://user-images.githubusercontent.com/63001005/125409940-5c4e6180-e3f7-11eb-9b5d-fd0262e4a453.png">

**Comment by kogepanh** [comment]
確認しました、ありがとう！

**Comment by nkthkr** [comment]
画像横幅

**Comment by kogepanh** [comment]
佐藤先生からの指摘箇所

> トップページの写真はもうちょっと研究っぽいのが好みです．ロゴはかっこいいですね．情報系なので，フォントはもうちょっと軽い感じがいいですね（フォントがごついと機械系みたい？） 月例発表会の写真が大きいので，下までスクロールするのが大変かも．

**Comment by nkthkr** [comment]
フォントがどこのこと言うてるんかあんまわからん(明日相談します)

**Comment by nkthkr** [comment]
Noto sans weight 300追加，700→400，400→300で検討
