### ISSUE TITLE
スマホでメニューボタンが表示されない

### ISSUE THREAD

**Issue by kogepanh** [Kenny-NISLab/nislab#95]
また余裕ある時でいいし、確認をお願いします。

![スクリーンショット 2021-07-28 15 49 56](https://user-images.githubusercontent.com/49851726/127277205-b9d1f413-2e5a-471d-91f8-aa2f20d4f276.png)

**Comment by nkthkr** [comment]
ブランチ間違えた

**Comment by kogepanh** [comment]
まあそこまで影響ないし大丈夫やろ！笑
